### ISSUE TITLE
Export to terminal

### ISSUE THREAD

**Issue by soywod** [albertorestifo/github.vim#8]
First of all, nice theme :) I love it !

Is there a way to export this theme for term / iTerm ?

**Comment by albertorestifo** [comment]
Thanks! 

Right now I'm concentrating on transitioning the theme to the updated colors as well as refactoring it a bit to use pure vimscript instead of estilo, so I don't see myself creating a term palette anytime soon.

However, if you want to give it a shot, all the colors are defined [in the palette configuration](https://github.com/albertorestifo/github.vim/blob/master/estilo/palettes/github.yml)
